services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
   
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: data_pipeline_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000" # FastAPI
      - "3000:3000" # Dagster UI
    volumes:
      - .:/app
      - ./data:/app/data
  
    command: ["dagster", "dev", "-f", "kara_dagster_pipeline/repo.py", "-h", "0.0.0.0", "-p", "3000"]

volumes:
  postgres_data: